language: node_js
node_js:
  - "8"

os:
  - linux

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: pull-monorepo-docs #for testing purposes
  script:
    - /bin/bash ./update-readmes.sh
    - /bin/bash ./update-v4-readmes.sh
    - npm test
  email: slnode@ca.ibm.com
  name: StrongLoop Bot
    