language: node_js
node_js:
  - "8"

os:
  - linux

git:
  depth: 300

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: pull-monorepo-docs #for testing purposes
  include:
    - stage: copy v2,v3 readmes
      script: /bin/bash ./update-readmes.sh
      after_success: skip
    - stage: copy v4 readmes
      script: /bin/bash ./update-v4-readmes.sh
      after_success: skip
    - stage: copy v4 docs
      before_script:
      - npm install
      script:
      - npm test
      after_success:
      - npm start
    