language: node_js
node_js:
  - "8"

os:
  - linux

git:
  depth: 300

before_script:
  - npm install
  
script:
  - npm test

after_success:
  - npm start

jobs:
  include:
    - stage: copy v2,v3 readmes
      script: /bin/bash ./update-readmes.sh
      after_success: skip
      os:
        - linux
    - stage: copy v4 readmes
      script: /bin/bash ./update-v4-readmes.sh
      after_success: skip
      os:
        - linux

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
    